### ISSUE TITLE
setHighlightedDays does not work from inside a server callback

### ISSUE THREAD

**Issue by Amosss** [Applandeo/Material-Calendar-View#286]
Hi

I have the following code:
```
getMonthEventsDates(result -> {
            try {
                ArrayList<Long> jo = new Gson().fromJson(new JSONObject(result).getJSONArray("result").toString(), new TypeToken<ArrayList<Long>>() {}.getType());
                ArrayList<Calendar> events = new ArrayList<>();
                for (long item: jo) {
                    events.add(Utils.getInstance().epochToCalendar(item));
                }
                calendar.setHighlightedDays(events);
            } catch (Exception e) {                
            }
        });
```
When setHighlightedDays is called from within the callback of a server request, the days are not colored accordingly (green). Only when the user selects the day and then another day, it turns green. It looks like a refresh issue.

If I start the fragment when the calendar view is GONE and then I VISIBLE it after setting the highlighted days, then it works. I tried invalidate() and postInvalidate() but that didn't help.

Not sure if related but setOnPreviousPageChangeListener and setOnForwardPageChangeListener events are not always triggered and I have no idea what is the "rule" for it to be triggered or not).

**Comment by Kinses38** [comment]
Exact same issue, only with "disabledDaysLabelsColor"

**Comment by kormateusz** [comment]
Fixed in 1.9.0-rc02

**Comment by Bukhari386** [comment]
> Fixed in 1.9.0-rc02

Still experiencing the same behavior even in 1.9.0-rc03.
The server response works fine but when you call the same function from setOnForwardPageChangeListener/setOnPreviousPageChangeListener it does mark events at all.
